name: testing
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  http_parser: ^4.0.2
  mime: ^1.0.5
  provider: ^6.1.1
  image_picker: ^1.1.2
  file_picker: ^8.1.2
  shared_preferences: ^2.2.3
  connectivity_plus: ^6.0.9
  uuid: ^4.5.1
  intl: ^0.20.2
  timezone: ^0.10.1
  web_socket_channel: ^3.0.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
